AWSTemplateFormatVersion: "2010-09-09"
Description: DNS and certs for Mission Control

Resources:
  DNS: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      HostedZoneConfig: 
        Comment: "Hosted zone for use-mission-control.com"
      Name: "use-mission-control.com"

Outputs:
  ROOTHOSTEDZONE:
    Description: The the root hosted zone for the application
    Value: !Ref DNS
    Export:
      Name: RootHostedZone
  